// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxxxqmthymdepqvxsaxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4eHhxbXRoeW1kZXBxdnhzYXhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NzU3MjIsImV4cCI6MjA2MDM1MTcyMn0._JdpWljjIlgcVV9fZlF8M6OQXsJMwN5_Z0b4bcI5yyc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);